### ISSUE TITLE
OVH S3 HighPerformanceBucket

### ISSUE THREAD

**Issue by markbonfert** [yomovh/tf-at-ovhcloud#1]
How to create a standard s3 bucket is shown in /tf-at-ovhcloud)/s3_bucket_only/ 

But how do i create a HighPerformanceBucket? What Parameter must be set to change the storage type?

**Comment by yomovh** [comment]
Hello @markbonfert 

You will need to update the  `region` and `s3_endpoint` to the one for the high performance offer. 
This documentation [page](https://help.ovhcloud.com/csm/en-ie-public-cloud-storage-s3-location?id=kb_article_view&sysparm_article=KB0047393)  provides the complete and up to date endpoint list.

I will add this to the Readme.
