### ISSUE TITLE
Cannot create S3 Bucket with Pulumi

### ISSUE THREAD

**Issue by davemaul** [yomovh/tf-at-ovhcloud#5]
Hi @yomovh,

thanks for your example on creating S3 buckets in OVH public cloud with terraform. I'm trying to create an S3 bucket with the current AWS Classic Provider (`6.34.1`) which is generated from the default AWS Terraform Provider (`5.48.0`). Your example works like a charm, however my attempt fails with the following error message:

```
error getting S3 Bucket request payment: NotImplemented: The requested resource is not implemented
status code: 501, request id: txd61b8392442e4c858b8dd-0066420942, host id: txd61b8392442e4c858b8dd-0066420942
```

The problem seems to occur [here](https://github.com/hashicorp/terraform-provider-aws/blob/a30704e58a4df006a91cf375e259fe5981b5b556/internal/service/s3/bucket.go#L965) when the underlying terraform provider wants to fetch the current request payment field. This API seems not to be supported at OVH.

Is there any way to skip the part as I'm personally not interested in this information? Currently, the AWS provider for OVH isn't usable at all because the error fails the whole deployment.

Thanks in advance!

PS: This is my Pulumi AWS provider config:

```yaml
aws:region: de
aws:accessKey: <REDACTED>
aws:secretKey: <REDACTED>
aws:skipCredentialsValidation: true
aws:skipRequestingAccountId: true
aws:skipRegionValidation: true
aws:skipMetadataApiCheck: true
aws:endpoints:
  - s3: https://s3.de.io.cloud.ovh.net
```

And the piece of code creating the bucket:

```typescript
import * as aws from '@pulumi/aws';

new aws.s3.Bucket(name, {
  acl: aws.s3.CannedAcl.Private
}, { parent: this });
```

**Comment by davemaul** [comment]
Hi @yomovh,

are you responding to PRs on this repository, or should we create a support ticket at OVH instead? We're premium support customers, hence the question. :)

Kind regards
David

**Comment by yomovh** [comment]
Hello,

Sorry I missed the notification. 

I tested the S3 bucket example with 

```bash
❯ tofu -version
OpenTofu v1.7.0
on darwin_arm64
+ provider registry.opentofu.org/hashicorp/aws v5.54.1
+ provider registry.opentofu.org/ovh/ovh v0.45.0
```

and it is running fine. The warning seems to be expected since we are not using the provider with aws. 
```
aws_s3_bucket.b: Creating...
aws_s3_bucket.b: Creation complete after 2s [id=redacted-tf-s3-bucket-only]
aws_s3_bucket_server_side_encryption_configuration.example: Creating...
aws_s3_bucket_server_side_encryption_configuration.example: Creation complete after 0s [id=165dd794b8cb4c97826ccb95602376a8-tf-s3-bucket-only]
╷
│ Warning: AWS account ID not found for provider
│
│   with provider["registry.opentofu.org/hashicorp/aws"],
│   on s3_bucket_only.tf line 61, in provider "aws":
│   61: provider "aws" {
│
│ See https://registry.terraform.io/providers/hashicorp/aws/latest/docs#skip_requesting_account_id for implications.
│
│ (and one more similar warning elsewhere)
╵

Apply complete! Resources: 4 added, 0 changed, 0 destroyed.

Outputs:

access_key = "REDACTED "
secret_key = <sensitive>
```
I do not know pulumi. Can you upgrade the aws provider version to the same one ?

**Comment by davemaul** [comment]
The problem is fixed when using the `aws.s3.BucketV2` resource with pulumi and recent providers. Thanks!
